apiVersion: v1
kind: Service
metadata:
  name: monitorapp-service
  labels:
    app: monitorapp
spec:
  type: NodePort
  selector:
    app: monitorapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31139   # keep same assigned port
